.PHONY all:
all:
	gcc -D PART1 parts.c -o diskinfo
	gcc -D PART2 parts.c -o disklist
	gcc -D PART3 parts.c -o diskget
	gcc -D PART4 parts.c -o diskput
	gcc -D PART5 parts.c -o diskfix
	
.PHONY clean:
clean:
	-rm diskinfo disklist diskget diskput diskfix